export class SpeechPatternsUtil {
    static readonly SPEECH_CONTEXTS = [
        {
            phrases: [
                // 한국어
                '안녕하세요',
                '감사합니다',
                '죄송합니다',
                '네',
                '아니요',
                '면접',
                '질문',
                '답변',
                '경험',
                '프로젝트',
                '회사',
                '개발',
                '프로그래밍',
                '코딩',
                '기술',
                '스킬',
                'STT',
                'TTS',
                'AI',
                'API',
                'DB',
                'SQL',
                'HTML',
                'CSS',
                'JS',
                'JavaScript',
                'TypeScript',
                'React',
                'Vue',
                'Angular',
                'Node.js',
                'Python',
                'Java',
                'Spring',
                'Django',
                'AWS',
                'Docker',
                'Kubernetes',
                'Git',
                'GitHub',
                '프론트엔드',
                '백엔드',
                '풀스택',
                '데이터베이스',
                '서버',
                '클라이언트',
                '배포',
                '테스트',
                '디버깅',
                // 영어
                'hello',
                'thank you',
                'sorry',
                'yes',
                'no',
                'interview',
                'question',
                'answer',
                'experience',
                'project',
                'company',
                'development',
                'programming',
                'coding',
                'technology',
                'skill',
            ],
            boost: 15.0,
        },
    ];
}
